server:
  port: 9010

spring:
  application:
    name: messages
  cloud:
    function:
      definition: sendEmail|sendSms
    stream:
      kafka:
        binder:
          brokers: localhost:9092 # Kafka broker address
      bindings:
        sendEmailsendSms-in-0:
          destination: send-communication # Logical broker destination. In Kafka, this maps to a topic named "send-communication".
          group: ${spring.application.name} # Defines the consumer group used for durable queue creation, workload sharing, and fault tolerance.
          # Based on the destination and group defined above, the Kafka binder will typically:
          # - create/use a topic named: send-communication
          # - register this microservice as part of consumer group: messages
          #   (since spring.application.name=messages)
          # - track consumed message offsets for this consumer group
          # - allow horizontal scaling by distributing messages across multiple instances
          # - automatically resume consumption from the last committed offset after restart
        sendEmailsendSms-out-0:
          destination: communication-sent

logging:
  level:
    com.microservices.messages.functions: DEBUG