server:
  port: 8091
spring:
  application:
    name: loans
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: qa
  config:
    import: "optional:configserver:http://localhost:8071"

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Exposing all actuator endpoints (we can expose specific endpoints in production for security reasons)
  endpoint:
    shutdown:
      enabled: true  # Enable shutdown endpoint
  info:
    env:
      enabled: true  # Enable environment info in actuator endpoints

eureka:
  client:
    register-with-eureka: true  # Enable registration with Eureka server
    fetch-registry: true  # Enable fetching registry information from Eureka server
    service-url:
      defaultZone: http://localhost:8070/eureka/  # Eureka server URL
  instance:
    prefer-ip-address: true  # Prefer IP address over hostname for service registration

info:
  app:
    name: loans-service
    description: "XYZ Bank Loans Application"
    version: 1.0.0