# defining common-config start here:
x-network-deploy-service: &network-deploy-service
  networks:
    - XYZBank

x-microservice-base-config: &microservice-base-config
  <<: *network-deploy-service
  deploy:
    resources:
      limits:
        memory: 700M

x-healthcheck: &healthcheck
  interval: 10s
  timeout: 5s
  retries: 10
  start_period: 10s

x-microservice-config: &microservice-config
  <<: *microservice-base-config
  depends_on:
    configserver:
      condition: service_healthy
    eurekaserver:
      condition: service_healthy

x-microservice-env: &microservice-env
  SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
  SPRING_PROFILES_ACTIVE: "qa"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"

x-gateway-ms-config: &gateway-ms-config
  <<: *microservice-base-config
  depends_on:
    accounts:
      condition: service_healthy
    loans:
      condition: service_healthy
    cards:
      condition: service_healthy
  environment:
    SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"

# defining common-config ends here

# our service definitions start here:
services:
  keycloak:
    <<: *network-deploy-service
    image: "quay.io/keycloak/keycloak:26.6"
    container_name: "keycloak"
    ports:
      - "7080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
    command: start-dev # Using start-dev for development purposes (not recommended for production use).

  rabbitmq:
    <<: *network-deploy-service
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672" # RabbitMQ default port for messaging
      - "15672:15672" # RabbitMQ management UI port
    environment:
      - CONNECTION_TIMEOUT=10000ms

  # Our application services configurations start here:
  configserver:
    <<: *microservice-base-config
    image: "abhinavyishu/configserver:v8.0"
    container_name: "configserver-ms"
    ports:
      - "8071:8071"
    healthcheck:
      <<: *healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:8071/actuator/health/readiness"]

  eurekaserver:
    <<: *microservice-base-config
    image: "abhinavyishu/eurekaserver:v8.0"
    container_name: "eurekaserver-ms"
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      <<: *healthcheck
      test: [ "CMD", "curl", "-f", "http://localhost:8070/actuator/health/readiness" ]
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"

  accounts:
    <<: *microservice-config
    image: "abhinavyishu/accounts:v8.0"
    container_name: "accounts-ms"
    # We can remove port mapping for accounts microservices as it is not accessed directly from
    # outside, but only through gateway. Hence, securing the microservice by not exposing it to
    # outside world.
    healthcheck:
      <<: *healthcheck
      retries: 20
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health/readiness" ]
    environment:
      <<: *microservice-env
      SPRING_RABBITMQ_HOST: "rabbitmq"

  loans:
    <<: *microservice-config
    image: "abhinavyishu/loans:v8.0"
    container_name: "loans-ms"
    # We can remove port mapping for lonas microservices as it is not accessed directly from
    # outside, but only through gateway. Hence, securing the microservice by not exposing it to
    # outside world.
    healthcheck:
      <<: *healthcheck
      retries: 20
      test: [ "CMD", "curl", "-f", "http://localhost:8091/actuator/health/readiness" ]
    environment:
      <<: *microservice-env

  cards:
    <<: *microservice-config
    image: "abhinavyishu/cards:v8.0"
    container_name: "cards-ms"
    # We can remove port mapping for cards microservices as it is not accessed directly from
    # outside, but only through gateway. Hence, securing the microservice by not exposing it to
    # outside world.
    healthcheck:
      <<: *healthcheck
      retries: 20
      test: [ "CMD", "curl", "-f", "http://localhost:9002/actuator/health/readiness" ]
    environment:
      <<: *microservice-env

  gateway-ms:
    <<: *gateway-ms-config
    image: "abhinavyishu/gateway:v8.0"
    container_name: "gateway-ms"
    ports:
      - "8072:8072"

  messages:
    <<: *microservice-config
    image: "abhinavyishu/messages:v8.0"
    container_name: "messages-ms"
    environment:
      SPRING_RABBITMQ_HOST: "rabbitmq"

# defining the network
networks:
  XYZBank:
    driver: bridge