server:
  port: 8072

spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:http://localhost:8071"
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: account-service
              uri: lb://ACCOUNTS
              predicates:
                - Path=/xyzbank/accounts/api/**
              filters:
                - StripPrefix=2
                - name: CircuitBreaker
                  args:
                    name: accountsCircuitBreaker
                    fallbackUri: forward:/contactSupport
              order: -1


management:
  endpoints:
    web:
      exposure:
        include: "*"  # This will expose all actuator endpoints.
  info:
    env:
      enabled: true  # Enable environment info in actuator endpoints
  endpoint:
    gateway:
      enabled: true # Enable the gateway actuator endpoint to monitor the routes and filters.
      # By default, in Spring Cloud Gateway 4.x and above (Spring Boot 3.x+), the gateway
      # actuator endpoint is disabled for security reasons. We need to explicitly enable it.

info:
  app:
    name: gateway-service
    description: "XYZ Bank Gateway Application"
    version: 1.0.0


logging:
  level:
    com.microservices.gateway: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default: # We can define configuration for a particular circuit breaker by replacing 'default' with the name of the circuit breaker (e.g., accountsCircuitBreaker)
        slidingWindowSize: 6
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10000 # 10 seconds before moving to half-open state
  timelimiter:
    configs:
      default:
        timeoutDuration: 5000 # 5 seconds timeout for calls to downstream services