server:
  port: 8072

spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:http://localhost:8071"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true  # Enable service discovery for the gateway to automatically route to registered services.
              lower-case-service-id: true  # Convert service IDs to lower case for consistent routing.


management:
  endpoints:
    web:
      exposure:
        include: "*"  # This will expose all actuator endpoints.
  info:
    env:
      enabled: true  # Enable environment info in actuator endpoints
  endpoint:
    gateway:
      enabled: true # Enable the gateway actuator endpoint to monitor the routes and filters.
      # By default, in Spring Cloud Gateway 4.x and above (Spring Boot 3.x+), the gateway
      # actuator endpoint is disabled for security reasons. We need to explicitly enable it.

info:
  app:
    name: gateway-service
    description: "XYZ Bank Gateway Application"
    version: 1.0.0
