server:
  port: 8081  # will remain same on all environments
spring:
  application:
    name: accounts  # will remain same on all environments
  # For now let us assume database related properties are same across all environments
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: qa  # setting qa as active profile
  config:
    import: "optional:configserver:http://localhost:8071"  # Importing configuration from config server

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Exposing all actuator endpoints (we can expose specific endpoints in production for security reasons)