services:
  rabbit:
    image: "rabbitmq:3.13-management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - XYZBank

  configserver:
    image: "abhinavyishu/configserver:v1.0"
    container_name: "configserver-ms"
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8071/actuator/health/readiness"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - XYZBank

  accounts:
    image: "abhinavyishu/accounts:v1.0"
    container_name: "accounts-ms"
    ports:
      - "8081:8081"
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700M
    environment:
#      SPRING_APPLICATION_NAME: "accounts" # Not required since we already defined in application.yml
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: "default"
    networks:
      - XYZBank

  loans:
    image: "abhinavyishu/loans:v1.0"
    container_name: "loans-ms"
    ports:
      - "8091:8091"
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700M
    environment:
#      SPRING_APPLICATION_NAME: "loans" # Not required since we already defined in application.yml
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: "default"
    networks:
      - XYZBank

  cards:
    image: "abhinavyishu/cards:v1.0"
    container_name: "cards-ms"
    ports:
      - "9002:9002"
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700M
    environment:
#      SPRING_APPLICATION_NAME: "cards" # Not required since we already defined in application.yml
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071" # Intsead of localhost using the service name of configserver
      SPRING_PROFILES_ACTIVE: "default"
    networks:
      - XYZBank

# defining the network
networks:  # Not needed but let us define it for better isolation and communication between services
    XYZBank:
        driver: bridge