# defining common-config start here:
x-network-deploy-service: &network-deploy-service
  networks:
    - XYZBank

x-microservice-base-config: &microservice-base-config
  <<: *network-deploy-service
  deploy:
    resources:
      limits:
        memory: 700M

x-healthcheck: &healthcheck
  interval: 10s
  timeout: 5s
  retries: 10
  start_period: 10s

x-microservice-config: &microservice-config
  depends_on:
    configserver:
      condition: service_healthy
    eurekaserver:
      condition: service_healthy
  environment:
    SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
    SPRING_PROFILES_ACTIVE: "prod"
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"

x-complete-microservice-config: &complete-microservice-config
  <<: [*microservice-config, *microservice-base-config]

x-gateway-ms-config: &gateway-ms-config
  <<: *microservice-base-config
  depends_on:
    accounts:
      condition: service_healthy
    loans:
      condition: service_healthy
    cards:
      condition: service_healthy
  environment:
    SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"

# defining common-config ends here

# our service definitions start here:
services:
  prometheus:
    <<: *network-deploy-service
    image: prom/prometheus:latest
    command: "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    volumes:
      - ../observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    healthcheck:
      <<: *healthcheck
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/ready"]

  grafana:
    <<: *network-deploy-service
    image: grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://prometheus:9090
        EOF
        /run.sh
    depends_on:
      prometheus:
        condition: service_healthy
    ports:
      - "3000:3000"

  # Our application services configurations start here:
  configserver:
    <<: *microservice-base-config
    image: "abhinavyishu/configserver:v5.0"
    container_name: "configserver-ms"
    ports:
      - "8071:8071"
    healthcheck:
      <<: *healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:8071/actuator/health/readiness"]

  eurekaserver:
    <<: *microservice-base-config
    image: "abhinavyishu/eurekaserver:v5.0"
    container_name: "eurekaserver-ms"
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      <<: *healthcheck
      test: [ "CMD", "curl", "-f", "http://localhost:8070/actuator/health/readiness" ]
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"

  accounts:
    <<: *complete-microservice-config
    image: "abhinavyishu/accounts:v5.0"
    container_name: "accounts-ms"
    ports:
      - "8081:8081"
    healthcheck:
      <<: *healthcheck
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health/readiness" ]

  loans:
    <<: *complete-microservice-config
    image: "abhinavyishu/loans:v5.0"
    container_name: "loans-ms"
    ports:
      - "8091:8091"
    healthcheck:
      <<: *healthcheck
      test: [ "CMD", "curl", "-f", "http://localhost:8091/actuator/health/readiness" ]

  cards:
    <<: *complete-microservice-config
    image: "abhinavyishu/cards:v5.0"
    container_name: "cards-ms"
    ports:
      - "9002:9002"
    healthcheck:
      <<: *healthcheck
      test: [ "CMD", "curl", "-f", "http://localhost:9002/actuator/health/readiness" ]

  gateway-ms:
    <<: *gateway-ms-config
    image: "abhinavyishu/gateway:v5.0"
    container_name: "gateway-ms"
    ports:
      - "8072:8072"

# defining the network
networks:
  XYZBank:
    driver: bridge